package za.co.quantive.shared.config

/**
 * Android-specific build configuration
 * In a real app, these values would come from BuildConfig generated by Gradle
 */
class AndroidBuildConfig : BuildConfig {
    override val environment: Environment
        get() = when {
            // In a real app, this would check BuildConfig.BUILD_TYPE or similar
            isDebug -> Environment.DEVELOPMENT
            else -> Environment.PRODUCTION
        }

    override val versionName: String
        get() = "1.0.0" // Would come from BuildConfig.VERSION_NAME

    override val versionCode: Int
        get() = 1 // Would come from BuildConfig.VERSION_CODE

    override val buildTime: Long
        get() = java.lang.System.currentTimeMillis()

    override val isDebug: Boolean
        get() = true // Would come from BuildConfig.DEBUG
}

/**
 * Provides the platform-specific BuildConfig instance
 */
actual fun getPlatformBuildConfig(): BuildConfig = AndroidBuildConfig()
